safe: true
server: true
server_port: 4000
baseurl: /
url: http://localhost:4000

ftp_host: jstherightway.com
ftp_dir: /public_html/

pygments: true
markdown: maruku
permalink: date
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blahtex
    png_dir:    images/latex
    png_url:    /images/latex
